name: Run Scripts

on:
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run user_login.py
        run: python user_login.py
        continue-on-error: true

      - name: Run cart_page.py
        run: python cart_page.py
        continue-on-error: true

      - name: Run all_items_to_cart.py
        run: python all_items_to_cart.py
        continue-on-error: true
