name: Run Scripts

on:
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Use the latest

      - name: Set up Python
        uses: actions/setup-python@v3 # Use the latest version
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      ############################################################################

      - name: All items to cart
        run: python test/test_all_items_to_cart.py

      - name: Cart Page
        run: python test/test_cart_page.py

      - name: Locked user
        run: python test/test_locked_user.py

      - name: Remove items from cart
        run: python test/test_remove_items_from_cart.py

      - name: User login
        run: python test/test_user_login.py

      - name: Dog picture
        run: python test/test_img_recog.py
