name: Run Scripts

on:
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      ############################################################################

      - name: All items to cart
        run: ./test/test_all_items_to_cart.py

      - name: Cart Page
        run: ./test/python test_cart_page.py

      - name: Locked user
        run: ./test/python test_locked_user.py

      - name: Remove items from cart
        run: ./test/python test_remove_items_from_cart.py

      - name: User login
        run: ./test/python test_user_login.py

      - name: Dog picture
        run: ./test/python test_img_recog.py
